version: build-{build}

clone_depth: 1

skip_tags: true

os: Visual Studio 2015

environment:
  CMAKE_GENERATOR: "Visual Studio 14 2015"
  MSVCVERSION: "v140"
  MSVCYEAR: "vs2015"
  matrix:
    - platform: Win32
      configuration: DynRelease


matrix:
  fast_finish: false

init:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmake --version
  - msbuild /version
  - cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f

install:


clone_folder: C:\projects\libzmq

before_build:
  - cmd: set LIBZMQ_BUILDDIR=C:\projects\libzmq
  #- cmd: md "%LIBZMQ_BUILDDIR%"
  - cd "%LIBZMQ_BUILDDIR%"
  #- cmd: cmake -D CMAKE_C_FLAGS_RELEASE="/MT" -D CMAKE_C_FLAGS_DEBUG="/MTd" -D WITH_SODIUM=OFF -D WITH_TWEETNACL=OFF -G "%CMAKE_GENERATOR%" "%APPVEYOR_BUILD_FOLDER%"
  - cmd: cd C:\projects\libzmq\builds\msvc\vs2015\
  - cmd: "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" libzmq.sln /p:Configuration=DynRelease /p:Platform=x64
  - cmd: "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" libzmq.sln /p:Configuration=DynDebug /p:Platform=x64
  - cmd: "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" libzmq.sln /p:Configuration=DynRelease /p:Platform=Win32
  - cmd: "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" libzmq.sln /p:Configuration=DynDebug /p:Platform=Win32
  # - cmd: C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe ZeroMQ.sln /build /prj=libzmq /cfg="DynDebug|Win32,DynRelease|Win32,DynDebug|Win32,DynRelease|Win32"

build:
  parallel: true
  project: C:\projects\libzmq\builds\msvc\vs2015\libzmq.sln
  verbosity: minimal

after_build:
  # install CoApp for NuGet package
  - ps: (new-object net.webclient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
  - ps: $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
  - ps: Import-Module CoApp

  - cmd: cd %LIBZMQ_BUILDDIR%\bin\%Configuration%"
  - cmd: copy "%SODIUM_LIBRARY_DIR%\libsodium.dll" .
  - cmd: 7z a -y -bd -mx=9 libzmq.zip *.exe *.dll
  - ps: Push-AppveyorArtifact "libzmq.zip" -Filename "libzmq-${env:Platform}-${env:Configuration}.zip"
  # create NuGet package with CoApp
  - ps: cd C:\projects\libzmq/builds/nuget
  - ps: Write-NuGetPackage .\libzmq.autopkg
  - ps: Push-AppveyorArtifact "*.nupkg"

test_script:
  - cmd: cd "%LIBZMQ_BUILDDIR%"
  - cmd: ctest -C "%Configuration%" -V

