version: build-{build}

branches:
  only:
  - nuget

clone_depth: 1

skip_tags: true

os: Visual Studio 2015

environment:
  CMAKE_GENERATOR: "Visual Studio 14 2015"
  MSVCVERSION: "v140"
  MSVCYEAR: "vs2015"
  matrix:
    - platform: all
      configuration: all


matrix:
  fast_finish: false

init:
  - msbuild /version
  - cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f

install:
  - cmd: cd C:\projects
  - cmd: git clone --branch stable https://github.com/jedisct1/libsodium.git
  - cmd: cd C:\projects\libsodium\builds\msvc\vs2015\
  # build libsodium in all configurations
  - cmd: for %C in (DynRelease DynDebug StaticRelease StaticDebug LtcgRelease LtcgDebug) do (for %F in (Win32 x64) do (MSBuild.exe libsodium.sln /p:Configuration=%C /p:Platform=%F /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"))



clone_folder: C:\projects\libzmq

build_script:
  - cmd: set LIBZMQ_BUILDDIR=C:\projects\libzmq\bin
    # get cpp headers
  - cmd: cd C:\projects\libzmq
  - cmd: git submodule init
  - cmd: git submodule update
  - cmd: cd C:\projects\libzmq\builds\msvc\vs2015\
  # build libzmq in all configurations
  - cmd: for %C in (DynRelease DynDebug StaticRelease StaticDebug LtcgRelease LtcgDebug) do (for %F in (Win32 x64) do (MSBuild.exe libzmq.sln /t:libzmq /p:Configuration=%C /p:Platform=%F /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"))

after_build:
  # install CoApp for NuGet package
  - ps: (new-object net.webclient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
  - ps: $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
  - ps: Import-Module CoApp

  # create NuGet package with CoApp
  - ps: cd C:\projects\libzmq\builds\nuget
  - ps: Write-NuGetPackage .\libzmq.autopkg
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  provider: NuGet
  api_key:
    secure: kyNQKzUrAh5MncQ0UEIOj6hkNxxbGnNLGSW3Hlbi9HCG/+wOvSSDkz7qD+hT7lEf
  skip_symbols: false
  artifact: /.*\.nupkg/
