version: build-{build}

branches:
  only:
  - nuget

clone_depth: 1

skip_tags: true

os: Visual Studio 2015

environment:
  CMAKE_GENERATOR: "Visual Studio 14 2015"
  MSVCVERSION: "v140"
  MSVCYEAR: "vs2015"
  matrix:
    - platform: all
      configuration: all


matrix:
  fast_finish: false

init:
  - msbuild /version
  - cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f

install:


clone_folder: C:\projects\libzmq

build_script:
  - cmd: set LIBZMQ_BUILDDIR=C:\projects\libzmq\bin
  # build v140
  - cmd: cd C:\projects\libzmq\builds\msvc\vs2015\
  # build dynamic
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=DynRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=DynDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=DynRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=DynDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  #build static
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=StaticRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=StaticDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=StaticRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=StaticDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  # build ltcg
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=LtcgRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=LtcgDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=LtcgRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:Configuration=LtcgDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  #build v120

  # build dynamic
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=DynRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=DynDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=DynRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=DynDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  #build static
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=StaticRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=StaticDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=StaticRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=StaticDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  # build ltcg
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=LtcgRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=LtcgDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=LtcgRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v120 /p:Configuration=LtcgDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  #build v110

  # build dynamic
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=DynRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=DynDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=DynRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=DynDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  #build static
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=StaticRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=StaticDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=StaticRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=StaticDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  # build ltcg
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=LtcgRelease /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=LtcgDebug /p:Platform=x64 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=LtcgRelease /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: MSBuild.exe libzmq.sln /p:PlatformToolset=v110 /p:Configuration=LtcgDebug /p:Platform=Win32 /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


#build:
#  parallel: true
#  project: C:\projects\libzmq\builds\msvc\vs2015\libzmq.sln
#  verbosity: minimal

after_build:
  # install CoApp for NuGet package
  - ps: (new-object net.webclient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
  - ps: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
  - ps: $env:PSModulePath = $env:PSModulePath + ';C:\Program Files (x86)\Outercurve Foundation\Modules'
  - ps: Import-Module CoApp

  # create NuGet package with CoApp
  - ps: cd C:\projects\libzmq\builds\nuget
  - ps: Write-NuGetPackage .\libzmq.autopkg
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  provider: NuGet
  api_key:
    secure: kyNQKzUrAh5MncQ0UEIOj6hkNxxbGnNLGSW3Hlbi9HCG/+wOvSSDkz7qD+hT7lEf
  skip_symbols: false
  artifact: /.*\.nupkg/
